// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


//TODO: MAKE THE COMPANIONS WORK.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK_56ntl3vRds2iiiG4QvTR5ZCY0dUnAs',
    appId: '1:154166004472:web:69d47db8dab7e203afc90d',
    messagingSenderId: '154166004472',
    projectId: 'mudhkir-app',
    authDomain: 'mudhkir-app.firebaseapp.com',
    databaseURL: 'https://mudhkir-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mudhkir-app.firebasestorage.app',
    measurementId: 'G-5BH1DYNEZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeMV_Ug_725_WJQz7LntCFOGpOZbaShOE',
    appId: '1:154166004472:android:6e83aa26aa9fffbeafc90d',
    messagingSenderId: '154166004472',
    projectId: 'mudhkir-app',
    databaseURL: 'https://mudhkir-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mudhkir-app.firebasestorage.app',
  );
}
